# Generated by Django 5.2.10 on 2026-01-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="average_heartrate",
            field=models.IntegerField(default=0, help_text="Average heart rate (bpm)"),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="calories_burned",
            field=models.IntegerField(default=0, help_text="Total calories burned"),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="intensity",
            field=models.IntegerField(
                editable=False, help_text="Calculated intensity from 1 to 10"
            ),
        ),
    ]
